# Generated by Django 4.1.7 on 2023-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground_api', '0002_remove_playground_created_at_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='address',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playground',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
