# Generated by Django 4.1.7 on 2023-03-09 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playground_api', '0004_remove_playground_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='place_id',
            field=models.TextField(default=uuid.UUID('88e6bfc4-9382-413e-a1cf-f46a4e13e6b2')),
        ),
    ]
