# Generated by Django 4.1.7 on 2023-03-10 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playground_api', '0006_alter_playground_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='playground',
            name='place_id',
            field=models.TextField(default=uuid.UUID('1eb9b756-c15d-4200-81f5-a5f71c1759ae')),
        ),
    ]
